45 shells
fishy smell
sedan stuck in mud
older footprints
webbed footprints
Gilman house hotel
4th floor is ours
3rd floor fishy smell
innsmouth cafe
Grace

Bryce Fallon - Hired us
professor leiter went missing oily / was doing dodgy gambler 
    massive heart attack 
    specialist in colonial history
    eyes boiled
    gut bacteria dead
    played a high roller but failed
    undead

abner wick art dealer
amelia court student 19
john wheatcroft tutor/coroner
hibs roadhouse 
casino chip
artwork cecil hunter - insane
professor roach history 

» Joseph Sutton first sought Dr. Harrod’s assistance in mid-July of last year. 
» Mr. Sutton was suffering from repeated and horrific nightmares that he was unable to recall. 
» He would wake up nearly every night screaming. This put a terrible strain on his marriage and left him irritable and exhausted. 
» Mr. Sutton experienced these nightmares for several weeks before seeking Dr. Harrod’s help.
» He saw Mr. Sutton twice a week from mid-July until just before his death. 
» Mr. Sutton was making progress, as he began to remember more of his dreams. 
» While his nightmares had not abated, he was beginning to form an understanding of what they might represent.
Left hand crippled
Crane st (house)
Phobia of the cold

Saw the grave

Brother Stuart sutton (Suspect)
Wife
 
wife brother  affair


* suspect
    - Amelia
    - Roach